spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3309/wmc-projekt
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true

# Hibernate-Konfiguration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Weitere Hibernate-Eigenschaften können hier hinzugefügt werden

# Optional: SQL-Anweisungen auf der Konsole anzeigen
spring.jpa.show-sql=true